inherit_gem:
  bixby: bixby_default.yml

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'

RSpec/MessageSpies:
    EnforcedStyle: receive

Layout/LeadingCommentSpace:
    Enabled: false

Lint/EmptyWhen:
    Exclude:
      - app/models/marc_indexer.rb

Metrics/ClassLength:
    Exclude:
        - 'spec/**/*'
        - 'app/controllers/catalog_controller.rb'
        - 'app/models/marc_indexer.rb'

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'
        - 'app/controllers/catalog_controller.rb'
        - 'config/routes.rb'

Metrics/LineLength:
    Exclude:
        - 'spec/**/*'

Metrics/AbcSize:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/CyclomaticComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/MethodLength:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/ModuleLength:
    Exclude:
        - 'lib/blacklight/access_controls/ability.rb'

Metrics/PerceivedComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

RSpec/DescribeClass:
    Exclude:
        - 'spec/system/visibility_spec.rb'

RSpec/ExampleLength:
    Exclude:
        - 'spec/**/*'
