inherit_gem:
  bixby: bixby_default.yml

AllCops:
    TargetRubyVersion: 2.7
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'

Layout/LeadingCommentSpace:
    Enabled: false

Layout/LineLength:
    Exclude:
        - 'spec/**/*'

Lint/EmptyWhen:
    Exclude:
      - app/models/marc_indexer.rb

Metrics/AbcSize:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'
        - 'app/controllers/catalog_controller.rb'
        - 'config/routes.rb'
        - 'coverage/config/routes.rb'

Metrics/ClassLength:
    Exclude:
        - 'spec/**/*'
        - 'app/controllers/catalog_controller.rb'
        - 'app/models/marc_indexer.rb'

Metrics/CyclomaticComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/MethodLength:
    Exclude:
        - 'app/models/marc_indexer.rb'
        - 'app/values/uv_configuration.rb'

Metrics/ModuleLength:
    Exclude:
        - 'lib/blacklight/access_controls/ability.rb'
        - 'app/helpers/blacklight/blacklight_helper_behavior.rb'

Metrics/PerceivedComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

Rails/Exit:
    Exclude:
        - 'config/deploy.rb'

Rails/Output:
    Exclude:
        - 'config/deploy.rb'

RSpec/AnyInstance:
    Exclude:
        - 'spec/**/*'

RSpec/DescribeClass:
    Exclude:
        - 'spec/system/visibility_spec.rb'
        - 'spec/routing/uv_config_routes_spec.rb'

RSpec/ExampleLength:
    Exclude:
        - 'spec/**/*'

RSpec/MessageSpies:
    EnforcedStyle: receive

Style/MethodDefParentheses:
  Exclude:
        - 'app/helpers/blacklight/blacklight_helper_behavior.rb'
