version: 2.1
orbs:
    qlty-orb: qltysh/qlty-orb@0.1.1
    samvera: samvera/circleci-orb@1.0.0
    browser-tools: circleci/browser-tools@1.4
jobs:
    build:
        parameters:
            ruby_version:
                type: string
                default: '3.1.2'
            bundler_version:
                type: string
                default: '2.3.22'
            solr_port:
                type: string
                default: '8985'
            redis_version:
                type: string
                default: '4'
            mysql_version:
                type: string
                default: '8.0.33'
        environment:
            BUNDLE_PATH: vendor/bundle
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
            RAILS_ENV: test
            RACK_ENV: test
            SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress --tag ~relevancy:true
            DATABASE_NAME: circle_test
            DATABASE_HOST: 127.0.0.1
            DATABASE_PORT: 3306
            DATABASE_USERNAME: root
        docker:
            - image: cimg/ruby:<< parameters.ruby_version >>-browsers
            - image: solr:7-alpine
              command: bin/solr -cloud -noprompt -f -p <<parameters.solr_port>>
            - image: circleci/redis:<<parameters.redis_version>>
            - image: cimg/mysql:<<parameters.mysql_version>>
        working_directory: ~/project
        parallelism: 4
        steps:
            - checkout
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver

            - samvera/bundle:
                ruby_version: << parameters.ruby_version >>
                bundler_version: << parameters.bundler_version >>

            - samvera/rubocop

            - run:
                name: Get yarn version
                command: echo $(yarn --version) >> "YARN_VERSION"

            - restore_cache:
                keys:
                  - v1-yarn-{{ checksum "yarn.lock" }}-{{ checksum "YARN_VERSION" }}

            - run: yarn

            - save_cache:
                key: v1-yarn-{{ checksum "yarn.lock" }}-{{ checksum "YARN_VERSION" }}
                paths:
                  - ~/project/node_modules

            - samvera/install_solr_core:
                solr_config_path: ./solr/conf

            - run:
                name: Wait for MySQL, if necessary.
                command: dockerize -wait tcp://${DATABASE_HOST}:${DATABASE_PORT} -timeout 1m

            - run: 
                name: Run migrations
                command: bundle exec rails db:migrate RAILS_ENV=test

            - samvera/parallel_rspec

            - qlty-orb/coverage_publish:
                files: coverage/.resultset.json
                incomplete: true
                total_parts_count: 4

            - store_artifacts:
                path: tmp/screenshots

    coverage:
        docker:
            - image: cimg/ruby:3.1.2
        working_directory: ~/project
        parallelism: 1
        steps:
            - qlty-orb/coverage_complete

workflows:
    version: 2
    ci:
        jobs:
            - build:
                name: rspec
            - coverage:
                name: qlty
                requires:
                    - rspec
