version: 2.1
orbs:
    samvera: samvera/circleci-orb@0.3.1
jobs:
    build:
        parameters:
            ruby_version:
                type: string
                default: '2.5.3'
            bundler_version:
                type: string
                default: '2.0.1'
            solr_port:
                type: string
                default: '8985'
            redis_version:
                type: string
                default: '4'
            mysql_version:
                type: string
                default: '5.7.22'
        environment:
            BUNDLE_PATH: vendor/bundle
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
            RAILS_ENV: test
            RACK_ENV: test
            SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress --tag ~relevancy:true
            DATABASE_NAME: circle_test
            DATABASE_HOST: 127.0.0.1
            DATABASE_PORT: 3306
            DATABASE_USERNAME: root
            READING_ROOM_IPS: 127.0.0.1
        docker:
            - image: circleci/ruby:<< parameters.ruby_version >>-node-browsers-legacy
            - image: solr:7-alpine
              command: bin/solr -cloud -noprompt -f -p <<parameters.solr_port>>
            - image: circleci/redis:<<parameters.redis_version>>
            - image: circleci/mysql:<<parameters.mysql_version>>
        working_directory: ~/project
        parallelism: 4
        steps:
            - checkout

            - samvera/bundle:
                ruby_version: << parameters.ruby_version >>
                bundler_version: << parameters.bundler_version >>

            - samvera/rubocop

            - run:
                name: Get yarn version
                command: echo $(yarn --version) >> "YARN_VERSION"

            - restore_cache:
                keys:
                  - v1-yarn-{{ checksum "yarn.lock" }}-{{ checksum "YARN_VERSION" }}

            - run: yarn

            - save_cache:
                key: v1-yarn-{{ checksum "yarn.lock" }}-{{ checksum "YARN_VERSION" }}
                paths:
                  - ~/project/node_modules

            - samvera/install_solr_core:
                solr_config_path: ./solr/conf

            - run:
                name: Install Code Climate test reporter
                command: |
                    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                    chmod +x ./cc-test-reporter
                    ./cc-test-reporter before-build

            # Dockerize is installed in CircleCI docker images by default.
            - run:
                name: Wait for MySQL, if necessary.
                command: dockerize -wait tcp://${DATABASE_HOST}:${DATABASE_PORT} -timeout 1m

            - samvera/parallel_rspec

            - run:
                name: Generate CC coverage
                command:  ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"

            - persist_to_workspace:
                root: coverage
                paths: codeclimate.*.json

            - store_artifacts:
                path: tmp/screenshots

            - deploy:
                command: curl -k https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN} -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"

    coverage:
        docker:
            - image: circleci/ruby:2.5.3
        working_directory: ~/project
        parallelism: 1
        steps:
            - attach_workspace:
                at: /tmp/codeclimate

            - run:
                name: Install Code Climate test reporter
                command: |
                    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                    chmod +x ./cc-test-reporter

            - run:
                name: Upload Coverage
                command: |
                    ./cc-test-reporter sum-coverage --output='/tmp/codeclimate/summed_coverage.json' /tmp/codeclimate/codeclimate.*.json
                    ./cc-test-reporter upload-coverage --input='/tmp/codeclimate/summed_coverage.json'

workflows:
    version: 2
    ci:
        jobs:
            - build:
                name: ruby2-5-3
            - coverage:
                name: codeclimate
                requires:
                    - ruby2-5-3
