rights_holders_tesim: 'Rights Holder'
human_readable_copyright_date_tesim: 'Copyright Date'
human_readable_re_use_license_tesim: 'Re-Use License'
access_restriction_notes_tesim: 'Access Restrictions'
