conference_dates_tesim: 'Conference Dates'
conference_name_tesim: 'Event / Conference Name'
sponsor_tesim: 'Sponsor'
data_producers_tesim: 'Data Producer'
grant_agencies_tesim: 'Grant / Funding Agency'
grant_information_tesim: 'Grant / Funding Information'
author_notes_tesim: 'Author Notes'
data_source_notes_tesim: 'Data Source Notes'
geographic_unit_tesim: 'Geographic Level for Dataset'
technical_note_tesim: 'Technical Note'
