emory_rights_statements_tesim: 'Rights Statement'
rights_statement_tesim: 'Rights Statement - Controlled'
rights_holders_tesim: 'Rights Holder'
copyright_date_tesim: 'Copyright Date'
re_use_license_tesim: 'Re-Use License'
access_restriction_notes_tesim: 'Access Restrictions'
