system_of_record_ID_tesim: 'System of Record ID'
emory_ark_tesim: 'Emory ARK'
other_identifiers_tesim: 'Other Identifiers'
institution_tesim: 'Institution'
holding_repository_tesim: 'Library'
administrative_unit_tesim: 'Administrative Unit'
sublocation_tesim: 'Sublocation'
local_call_number_tesim: 'Call Number'
contact_information_tesim: 'Contact Information'
