publisher_tesim: 'Publisher'
final_published_versions_tesim: 'Final Published Version'
publisher_version_tesim: 'Version of Publication'
place_of_production_tesim: 'Place of Publication/Production'
volume_tesim: 'Volume'
edition_tesim: 'Edition'
issue_tesim: 'Issue'
page_range_start_tesim: 'Page Range - Start'
page_range_end_tesim: 'Page Range - End'
issn_tesim: 'ISSN'
isbn_tesim: 'ISBN'
