subject_topics_tesim: 'Subject - Topics'
subject_names_tesim: 'Subject - Names'
subject_geo_tesim: 'Subject - Geographic Locations'
subject_time_periods_tesim: 'Subject - Time Periods'
keywords_tesim: 'Keywords'
