# frozen_string_literal: true
COLLECTION = {
  has_model_ssim: ["Collection"],
  visibility_ssi: "open",
  read_access_group_ssim: ["public"],
  id: "119f4qrfj9-cor",
  accessControl_ssim: ["38cd37a4-9437-4ecf-868f-bbdb290b2341"],
  title_tesim: ["Chester W. Topp collection of Victorian yellowbacks and paperbacks"],
  title_sim: ["Chester W. Topp collection of Victorian yellowbacks and paperbacks"],
  collection_type_gid_ssim: ["gid://dlp-curate/curate-collectiontype/1"],
  abstract_tesim: ["Collection of yellowbacks and paperbacks collected by Chester W. Topp.  Yellowbacks are cheap novels published in the late nineteenth and early twentieth century in Great Britain."],
  administrative_unit_tesim: ["Stuart A. Rose Manuscript, Archives, and Rare Book Library"],
  contact_information_tesim: ["Rose Library\r\nWoodruff Library\r\nEmory University \r\n540 Asbury Circle\r\nAtlanta, GA 30322 \r\nrose.library@emory.edu\r\n404-727-6887"],
  contributors_tesim: ["Someone else"],
  creator_tesim: ["Topp, Chester W., collector."],
  creator_sim: ["Topp, Chester W., collector."],
  emory_ark_tesim: ["https://yellowbacks.digitalscholarship.emory.edu/"],
  finding_aid_link_ssm: ["https://my-finding-aid.com"],
  holding_repository_tesim: ["Stuart A. Rose Manuscript, Archives, and Rare Book Library"],
  holding_repository_sim: ["Stuart A. Rose Manuscript, Archives, and Rare Book Library"],
  institution_tesim: ["Emory University"],
  local_call_number_tesim: ["YELLOWBACKS"],
  primary_language_tesim: ["eng"],
  primary_language_sim: ["eng"],
  member_ids_ssim: [],
  notes_tesim: ["a brief note"],
  object_ids_ssim: [],
  member_of_collections_ssim: ['A pretend Parent collection for the Yellowbacks Collection'],
  member_of_collection_ids_ssim: ['805fbg79d6-cor'],
  collection_ids_ssim: [],
  thumbnail_path_ss: "/downloads/2150gb5mmj-cor?file=thumbnail",
  generic_type_sim: ["Collection"],
  bytes_lts: 312_470_524,
  edit_access_person_ssim: ["tmiles2"],
  human_readable_type_sim: "Collection",
  human_readable_type_tesim: "Collection",
  member_works_count_isi: 3
}.freeze
