# frozen_string_literal: true
CURATE_GENERIC_WORK = {
  id: ['123'],
  has_model_ssim: ['CurateGenericWork'],
  visibility_ssi: ['open'],
  title_tesim: ['The Title of my Work'],
  uniform_title_tesim: ['This is a uniform title'],
  series_title_tesim: ['This is a series title'],
  parent_title_tesim: ['This is a parent title'],
  creator_tesim: ['Smith, Somebody'],
  contributors_tesim: ['Contributor, Jack'],
  date_created_tesim: ['1776', 'XXXX', '192?', '1973?'],
  date_issued_tesim: ['1652'],
  data_collection_dates_tesim: ['1985'],
  human_readable_content_type_tesim: ['Text'],
  content_type_tesim: ['http://id.loc.gov/vocabulary/resourceTypes/txt'],
  content_genres_tesim: ['Painting'],
  extent_tesim: ['152 p., [50] leaves of plates'],
  primary_language_tesim: ['English'],
  notes_tesim: ['notes about a thing'],
  abstract_tesim: ['Description or abstract of work'],
  table_of_contents_tesim: ['Table of contents, Here\'s another content'],
  subject_topics_tesim: ['A topic for a subject'],
  subject_names_tesim: ['Qāsimlū, Mujtabá'],
  subject_geo_tesim: ['New Jersey'],
  subject_time_periods_tesim: ['Edo (African)'],
  keywords_tesim: ['key', 'words'],
  system_of_record_ID_tesim: ['System of record ID seems to be a user entered string'],
  emory_ark_tesim: ['This is a legacy Emory ARK ID'],
  other_identifiers_tesim: ['oclc:(OCoLC)772049332', 'barcode:050000087509'],
  institution_tesim: ['Emory University'],
  holding_repository_tesim: ['Oxford College Library'],
  administrative_unit_tesim: ['Stuart A. Rose Manuscript, Archives, and Rare Book Library'],
  sublocation_tesim: ['That weird cart in the third basement'],
  local_call_number_tesim: ['ML450.B613 v. 3'],
  contact_information_tesim: ['Call Milly']
}.freeze
