# frozen_string_literal: true
PARENT_CURATE_GENERIC_WORK = {
  system_create_dtsi: "2020-01-13T19:25:30Z",
  system_modified_dtsi: "2020-01-14T19:40:00Z",
  has_model_ssim: ["CurateGenericWork"],
  id: "030prr4xkj-cor",
  accessControl_ssim: ["6ae1ab19-50f0-46f6-b3de-8e0c597dea58"],
  hasRelatedMediaFragment_ssim: ["433dz08ksb-cor"],
  hasRelatedImage_ssim: ["433dz08ksb-cor"],
  depositor_ssim: ["eporter"],
  depositor_tesim: ["eporter"],
  title_tesim: ["Emocad."],
  title_sim: ["Emocad."],
  date_uploaded_dtsi: "2020-01-13T19:26:26Z",
  date_modified_dtsi: "2020-01-14T19:40:58Z",
  isPartOf_ssim: ["admin_set/default"],
  content_type_tesim: ["http://id.loc.gov/vocabulary/resourceTypes/txt"],
  content_type_sim: ["http://id.loc.gov/vocabulary/resourceTypes/txt"],
  contributors_tesim: ["Emory University Archives", "Emory University Academy (Oxford, Ga.)"],
  creator_tesim: ["Sample Parent Creator"],
  data_classifications_tesim: ["Public"],
  date_created_tesim: ["1919/192X"],
  date_created_sim: ["1919/192X"],
  date_created_dtsim: [],
  date_created_si: "1919/192X",
  date_digitized_tesim: ["2017"],
  date_digitized_dtsim: [],
  date_digitized_sim: ["2017"],
  date_issued_tesim: ["1919/192X"],
  date_issued_dtsim: [],
  date_issued_sim: ["1919/192X"],
  date_issued_si: "1919/192X",
  emory_rights_statements_tesim: ["The online edition of this book in the public domain, i.e., not protected by copyright, has been produced by the Emory University Digital library Publications Program "],
  holding_repository_tesim: ["Oxford College Library (Oxford, Ga.)"],
  holding_repository_sim: ["Oxford College Library (Oxford, Ga.)"],
  institution_tesim: ["Emory University"],
  notes_tesim: ["Published by the Students of Emory University Academy ", "\"Emory University Academy ... was established in fall 1915\"--In Senior class history, pg. [16], 1919. "],
  place_of_production_tesim: ["Oxford, Georgia"],
  primary_language_tesim: ["English"],
  primary_language_sim: ["English"],
  rights_statement_tesim: ["http://rightsstatements.org/vocab/NoC-US/1.0/"],
  rights_statement_sim: ["http://rightsstatements.org/vocab/NoC-US/1.0/"],
  subject_topics_tesim: ["College yearbooks--Georgia--Oxford."],
  subject_topics_sim: ["College yearbooks--Georgia--Oxford."],
  system_of_record_ID_tesim: ["alma:990030187270302486"],
  thumbnail_path_ss: "/downloads/433dz08ksb-cor?file=thumbnail",
  suppressed_bsi: false,
  actionable_workflow_roles_ssim: ["admin_set/default-default-managing", "admin_set/default-default-approving", "admin_set/default-default-depositing"],
  workflow_state_name_ssim: "deposited",
  member_ids_ssim: ["0859cnp5kv-cor", "423612jm8k-cor", "433dz08ksb-cor", "631cjsxkvx-cor", "85370rxwgx-cor"],
  member_of_collections_ssim: ["Emory University Yearbooks"],
  member_of_collection_ids_ssim: ["0278sf7m0d-cor"],
  generic_type_sim: ["Work"],
  file_set_ids_ssim: ["0859cnp5kv-cor", "423612jm8k-cor", "433dz08ksb-cor", "631cjsxkvx-cor", "85370rxwgx-cor"],
  visibility_ssi: "open",
  admin_set_sim: ["Default Admin Set"],
  admin_set_tesim: ["Default Admin Set"],
  preservation_workflow_terms_sim: [],
  human_readable_content_type_ssim: ["Text"],
  human_readable_rights_statement_ssim: ["No Copyright - United States"],
  human_readable_re_use_license_ssim: [nil],
  year_created_isim: nil,
  human_readable_date_created_tesim: ["within the 1919 or 1920s"],
  human_readable_date_issued_tesim: ["within the 1919 or 1920s"],
  year_issued_isim: nil,
  year_for_lux_isim: nil,
  human_readable_data_collection_dates_tesim: [],
  human_readable_conference_dates_tesim: [nil],
  human_readable_copyright_date_tesim: [nil],
  human_readable_type_sim: "Curate Generic Work",
  human_readable_type_tesim: "Curate Generic Work",
  read_access_group_ssim: ["public", "Repository Administrators", "repository_manager"],
  edit_access_group_ssim: ["admin", "Repository Administrators", "repository_manager"],
  edit_access_person_ssim: ["tmiles2", "eporter"],
  child_works_for_lux_tesim: [
    "423612jm8k-cor, /downloads/020fttdz2x-cor?file=thumbnail, Emocad. [1924]",
    "631cjsxkvx-cor, /downloads/0343r2282s-cor?file=thumbnail, Emocad. [1925]",
    "0859cnp5kv-cor, /downloads/211kh1895r-cor?file=thumbnail, Emocad. [1926]",
    "85370rxwgx-cor, /downloads/293gxd256t-cor?file=thumbnail, Emocad. [1928]"
  ]
}.freeze
