hero_images:
  - file: 931qfttf4h-cor.jpg
    name: Zushi containing an image of the Buddhist deity Benzaiten, one of the Seven Lucky Gods in Japan, detail
    path: https://digital.library.emory.edu/catalog/931qfttf4h-cor
  - file: 218dfn2z9j-cor.jpg
    name: Large disk-shaped Feng Shui compass, detail
    path: https://digital.library.emory.edu/catalog/218dfn2z9j-cor
  - file: 419s1rn8vh-cor.jpg
    name: Students at Clark Atlanta University dressed in costume holding a star, detail
    path: https://digital.library.emory.edu/catalog/914nk98sn6-cor
  - file: 385n8pk0tq-cor.jpg
    name: Five pictures of an African American woman in a dress wearing various hats in three pictures, no hat in two and with a flag behind her head in one without a hat, detail
    path: https://digital.library.emory.edu/catalog/385n8pk0tq-cor
  - file: 160cvdncr2-cor.jpg
    name: Pharmaceutical samples in a leather case owned by Henry S. Wright, detail
    path: https://digital.library.emory.edu/catalog/160cvdncr2-cor
  - file: 5805x69pct-cor.jpg
    name: "Jack McVea and his Orchestra : exclusive black & white recording artists, detail"
    path: https://digital.library.emory.edu/catalog/5805x69pct-cor
  - file: 358bg79cv6-cor.jpg
    name: 31 piece obstetrical instrumental set owned by Dr. C. W. Strickler, Jr., detail
    path: https://digital.library.emory.edu/catalog/358bg79cv6-cor
